apiVersion: apps/v1
kind: Deployment
metadata:
  name: psd2-obie-frontend
  labels:
    app: psd2-obie-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psd2-obie-frontend
  template:
    metadata:
      labels:
        app: psd2-obie-frontend
    spec:
      containers:
      - name: psd2-obie-frontend
        image: forgerock/psd2-obie-frontend:1.0
        ports:
        - containerPort: 80
        
---        
apiVersion: v1
kind: Service
metadata:
  name: psd2-obie-frontend
  labels:
    app: psd2-obie-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: psd2-obie-frontend