# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    client:
        enabled: true
        healthcheck:
            enabled: true
        fetch-registry: true
        register-with-eureka: true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
    instance:
        appname: psd2rscsevice
        instanceId: psd2rscsevice:${spring.application.instance-id:${random.value}}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        status-page-url-path: ${management.endpoints.web.base-path}/info
        health-check-url-path: ${management.endpoints.web.base-path}/health
        metadata-map:
            zone: primary # This is needed for the load balancer
            profile: ${spring.profiles.active}
            version: ${info.project.version:}
            git-version: ${git.commit.id.describe:}
            git-commit: ${git.commit.id.abbrev:}
            git-branch: ${git.branch:}
ribbon:
    eureka:
        enabled: true
feign:
    hystrix:
        enabled: true
#    client:
#        config:
#            default:
#                connectTimeout: 5000
#                readTimeout: 5000

# See https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix:
    command:
        default:
            execution:
                isolation:
                    strategy: SEMAPHORE
# See https://github.com/spring-cloud/spring-cloud-netflix/issues/1330
#                    thread:
#                        timeoutInMilliseconds: 10000
    shareSecurityContext: true

management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: ["configprops", "env", "health", "info", "threaddump", "logfile" ]
    endpoint:
        health:
            show-details: when-authorized
    info:
        git:
            mode: full
    health:
        mail:
            enabled: false # When using the MailService, configure an SMTP server and set this to true
    metrics:
        enabled: false # http://micrometer.io/ is disabled by default, as we use http://metrics.dropwizard.io/ instead

spring:
    application:
        name: psd2RSCSevice
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: HTML

server:
    #port: 8443
    #ssl:
        #key-alias: transport
        #key-password: changeit
        #key-store: classpath:config/tls/keystore.p12
        #key-store-password: changeit
    servlet:
        session:
            cookie:
                http-only: true

# Properties to be exposed on the /info management endpoint
info:
    # Comma separated list of profiles that will trigger the ribbon to show
    display-ribbon-on-profiles: "dev"

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
    async:
        core-pool-size: 2
        max-pool-size: 50
        queue-capacity: 10000
    # By default CORS is disabled. Uncomment to enable.
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        #exposed-headers: "Authorization,Link,X-Total-Count"
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: psd2RSCSevice@localhost
    swagger:
        default-include-pattern: /api/.*
        title: psd2RSCSevice API
        description: psd2RSCSevice API documentation
        version: 0.0.1
        terms-of-service-url:
        contact-name:
        contact-url:
        contact-email:
        license:
        license-url:

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

application:
    jwkms: https://jwkms.ob.forgerock.financial
    issuerID: forgerock-rcs
    rcs-issuer-id: forgerock-rcs
    am-cookie-name: iPlanetDirectoryPro
    am-jwk-url: ${rsc-remote-host.am}/oauth2/realms/root/realms/openbanking/connect/jwk_uri
    idm-get-payment-intent-consent-url: ${rsc-remote-host.idm}/openidm/managed/ObDomesticPayment/
    idm-update-payment-consent-url: ${rsc-remote-host.idm}/openidm/endpoint/obPaymentIntent/
    idm-get-account-intent-consent-url: ${rsc-remote-host.idm}/openidm/managed/ObAccountAccess/
    idm-update-account-consent-url: ${rsc-remote-host.idm}/openidm/endpoint/obAccountAccessIntent/
    am-auth-url: ${rsc-remote-host.am}/json/realms/root/authenticate
    am-jwk-url-connect-timeout: 100
    am-jwk-url-read-timeout: 100
    am-jwk-url-size-limit: 100000
    am-host-url: ${rsc-remote-host.am}
    am-get-cookie-token: ${rsc-remote-host.am}/json/realms/root/realms/openbanking/authenticate
    idm-consent-status-authorised : Authorised
    idm-consent-status-rejected : Rejected
    idm-consent-status-awaiting : AwaitingAuthorisation
    #idm-data-creaded-fromat: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    sca-time-auto-accept: 90
    sca-time-expire: 180    

    key-alias: transport
    key-password: changeit
    key-store: classpath:keystore/keystore.p12
    key-store-password: changeit    
        
        